### ISSUE TITLE
Installation by hand on Linux fails due to missing dependencies

### ISSUE THREAD

**Issue by nylander** [jordandouglas/ORC#2]
Hi!

I'm getting errors while attempting the ["By Hand"](https://github.com/jordandouglas/ORC#by-hand) installation on Linux:

```
$ cd BEAST2
$ ant linux
Buildfile: /home/nylander/src/BEAST2/BEAST2/build.xml

BUILD FAILED
/home/nylander/src/BEAST2/BEAST2/build.xml:407: taskdef class net.jsign.JsignTask cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds
```
Apparently this is due to not finding dependencies related to ["Jsign - A Java implementation of Microsoft Authenticode
for signing Windows executable files, installers and scripts"](https://ebourg.github.io/jsign/).

There is a discussion over at [Debian](https://www.mail-archive.com/debian-med@lists.debian.org/msg23351.html) where this also is mentioned, but the documentation for this repository surely needs to be updated.

Cheers
Johan

**Comment by rbouckaert** [comment]
Hi Johan, 

Are you on the  master branch, or on the v2.6 branch? The master branch of beast2 is worked on quite intensively to make a v2.7, but the v2.6 branch (ORC has not been updated to v2.7, so only works with v2.6 at the moment) should allow `ant linux` to run without hitches.

Cheers,

Remco
